### ISSUE TITLE
Helping contributors

### ISSUE THREAD

**Issue by DanCarl857** [achabill/garriblog#3]
Hello, love the repo, is it possible to update the issues list with tasks new contributors can work on? 
If you are too busy to do that you could send them to me and I add them.

**Comment by achabill** [comment]
garriBlog is still very underdeveloped that at this stage we can't have clear "beginner friendly/simple" tasks. 
Other contributors can raise any ideas of features they want and could work on it.
So maybe we have a roadmap so as to confine the scope.

**Comment by achabill** [comment]
I've added a useful features list.
https://github.com/achabill/garriblog#features

**Comment by DanCarl857** [comment]
Nice. So any roadmap document?
